- coordinates: 15, 20
  size: 10, 20
  items:
    - type: Sword
      coordinates: 1, 3
    - type: Hobgoblin
      coordinates: 3, 5
    - type: Hero
      coordinates: 7, 8
    - type: Potion
      coordinates: 6, 4
      strengh: 50
    - type: Gold
      coordinates: 5, 3
      amount: 50
    - type: Door
      coordinates: 0, 8
    - type: Door
      coordinates: 10, 19