- coordinates: 15, 20
  size: 10, 20
  items:
    - type: sword
      coordinates: 1, 3
    - type: hobgoblin
      coordinates: 3, 5
    - type: hero
      coordinates: 7, 8
    - type: potion
      coordinates: 6, 4
      strengh: 50
    - type: gold
      coordinates: 5, 3
      value: 50
    - type: door
      coordinates: 0, 8
    - type: door
      coordinates: 10, 19